### ISSUE TITLE
Идея на интеграцию

### ISSUE THREAD

**Issue by coolitydev** [bubochka14/KeyboardAnalyzer#1]
Нужно добавить, чтобы при нажатии кнопки запускался CYBERGRAM

**Comment by bubochka14** [comment]
Я рассмотрю ваше предложение

**Comment by bubochka14** [comment]
после того как обсужу с инвесторами и заинтересованными лицами

**Comment by bubochka14** [comment]
после того как обсужу с инвесторами и заинтересованными лицами
